"""Procedural silhouette layers.

These are deliberately NOT generated by diffusion. Mountain ridgelines, pine
treelines and skylines are flat hard-edged shapes, and a diffusion model gives
them mushy asymmetric edges that won't mirror, won't tile, and go soft the
moment you scale them. Generated mathematically they are crisp at any size,
horizontally seamless so they wrap the car, and pure alpha so they can be
recoloured in Clearcoat without regenerating anything.

Everything here is periodic in x by construction: the noise is a sum of sines
at integer frequencies, so the left edge always meets the right edge.
"""
import math
import random

from PIL import Image, ImageDraw, ImageFilter


def _periodic_noise(width, octaves, seed, base_freq=2):
    """Sum-of-sines noise, exactly periodic across `width`."""
    rng = random.Random(seed)
    terms = []
    for o in range(octaves):
        freq = base_freq * (2 ** o)
        terms.append((freq, rng.uniform(0, math.tau), 1.0 / (2 ** o)))
    out = []
    for x in range(width):
        t = x / width
        v = sum(amp * math.sin(math.tau * freq * t + phase) for freq, phase, amp in terms)
        out.append(v)
    peak = max(abs(v) for v in out) or 1.0
    return [v / peak for v in out]


def _ridge_profile(width, seed, roughness, sharpness, summits=7):
    """A ridgeline height profile in 0..1.

    Built from straight segments between summits rather than smoothed noise.
    Band-limited noise cannot produce a corner, so it always reads as rolling
    cloud - a mountain needs an actual apex where two straight flanks meet.
    Fine noise is added afterwards for crags, kept small so the peaks survive.
    """
    rng = random.Random(seed)
    n = max(3, int(summits))
    # Summits sit on an even grid with jitter capped at a quarter of the
    # spacing. That keeps them strictly increasing by construction, so no
    # sorting, clamping or gap-repair is needed - all of which can cascade
    # summits leftward and leave one long ramp across the whole range.
    step = 1.0 / n
    xs = [(i + 0.5 + rng.uniform(-0.25, 0.25)) * step for i in range(n)]
    hs = [rng.uniform(0.25, 1.0) ** (1.0 / max(0.4, sharpness)) for _ in range(n)]
    xs.append(xs[0] + 1.0)
    hs.append(hs[0])

    # Walk the segments and fill each pixel span directly. Scanning pixels and
    # advancing a segment cursor instead is a trap: the cursor only moves
    # forward, so the wrap-around pixels at the start push it to the last
    # segment and every remaining pixel then interpolates along that one span -
    # producing a single ramp across the whole range.
    prof = [0.0] * width
    for k in range(len(xs) - 1):
        x0, x1 = xs[k], xs[k + 1]
        h0, h1 = hs[k], hs[k + 1]
        span = (x1 - x0) or 1e-6
        for px in range(int(math.ceil(x0 * width)), int(math.ceil(x1 * width))):
            f = (px / width - x0) / span
            # Valleys dip below the straight line between two summits, or the
            # range reads as a row of tents.
            v = (h0 + (h1 - h0) * f) * (0.55 + 0.45 * abs(2 * f - 1))
            prof[px % width] = v

    crag = _periodic_noise(width, octaves=4, seed=seed + 991, base_freq=6)
    prof = [p + roughness * 0.06 * c for p, c in zip(prof, crag)]
    lo, hi = min(prof), max(prof)
    span = (hi - lo) or 1.0
    return [(v - lo) / span for v in prof]


def mountains(width=2048, height=768, layers=4, seed=7, roughness=1.0,
              sharpness=1.6, fade=True):
    """Layered mountain ridgelines, back layers lighter for aerial depth."""
    img = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    for i in range(layers):
        depth = i / max(1, layers - 1)          # 0 = furthest back
        # Distant ranges carry more, smaller summits; the front range is bolder.
        summits = int(round(11 - 5 * depth))
        prof = _ridge_profile(width, seed + i * 137, roughness, sharpness, summits)
        # Back ranges sit higher and are shorter; front ranges dominate.
        top = height * (0.16 + 0.20 * depth)
        amp = height * (0.20 + 0.28 * depth)
        pts = [(x, top + (1.0 - prof[x]) * amp) for x in range(width)]
        poly = pts + [(width - 1, height), (0, height)]

        alpha = int(255 * (0.45 + 0.55 * depth)) if fade else 255
        layer = Image.new("RGBA", (width, height), (0, 0, 0, 0))
        ImageDraw.Draw(layer).polygon(poly, fill=(255, 255, 255, alpha))
        img = Image.alpha_composite(img, layer)
    return img


def _tree(draw, x, base_y, h, w, seed):
    """One conifer: stacked tapering triangles."""
    rng = random.Random(seed)
    tiers = max(3, int(h / 26))
    trunk = max(1, int(w * 0.10))
    draw.rectangle([x - trunk, base_y - h * 0.10, x + trunk, base_y],
                   fill=(255, 255, 255, 255))
    for t in range(tiers):
        f = t / tiers
        ty = base_y - h * (0.10 + 0.90 * f)
        tw = w * (1.0 - 0.72 * f) * rng.uniform(0.92, 1.08)
        th = h * 0.30 * (1.0 - 0.35 * f)
        draw.polygon([(x - tw, ty), (x + tw, ty), (x, ty - th)],
                     fill=(255, 255, 255, 255))


def treeline(width=2048, height=512, seed=11, density=1.0, size=1.0, rows=2):
    """A horizontally seamless line of conifers along the bottom edge.

    Spacing is driven by tree WIDTH, not height. Deriving it from height packs
    tall trees so tightly they merge into one solid mass with no readable
    silhouette at all.
    """
    img = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    for r in range(rows):
        depth = r / max(1, rows - 1) if rows > 1 else 1.0
        layer = Image.new("RGBA", (width, height), (0, 0, 0, 0))
        d = ImageDraw.Draw(layer)
        rng = random.Random(seed + r * 313)

        base_h = height * (0.34 + 0.30 * depth) * size    # back row shorter
        base_w = base_h * 0.30
        spacing = base_w * 2.1 / max(0.25, density)
        n = max(4, int(width / spacing))
        step = width / n                                   # exact division keeps the wrap clean
        base_y = height * (0.86 + 0.14 * depth)

        for i in range(n + 1):
            x = (i * step + rng.uniform(-step * 0.18, step * 0.18)) % width
            h = base_h * rng.uniform(0.78, 1.22)
            w = h * rng.uniform(0.26, 0.34)
            for off in (0, -width, width):                 # wrapped copies at both edges
                if -w * 2 <= x + off <= width + w * 2:
                    _tree(d, x + off, base_y, h, w, seed + i * 17 + r)

        if depth < 1.0:                                    # fade the back rows
            a = int(255 * (0.55 + 0.45 * depth))
            layer.putalpha(layer.getchannel("A").point(lambda v: v * a // 255))
        img = Image.alpha_composite(img, layer)
    return img


def skyline(width=2048, height=512, seed=5, density=1.0):
    """Blocky city skyline — same idea, rectangles instead of triangles."""
    img = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    rng = random.Random(seed)

    # Lay the run out first, then scale it to close exactly on `width`. Without
    # this the final building is clipped mid-facade and the wrap shows a seam.
    plan, x = [], 0.0
    while x < width:
        w = rng.uniform(30, 130) / max(0.3, density)
        plan.append((x, w, height * rng.uniform(0.28, 0.92), rng.random() < 0.30,
                     rng.uniform(20, 70)))
        x += w + rng.uniform(2, 14)
    scale = width / x if x else 1.0

    for bx, bw, bh, spire, sh in plan:
        bx, bw = bx * scale, bw * scale
        for off in (0, -width, width):          # draw wrapped copies at both edges
            x0 = bx + off
            if x0 > width or x0 + bw < 0:
                continue
            d.rectangle([x0, height - bh, x0 + bw, height], fill=(255, 255, 255, 255))
            if spire:
                sx = x0 + bw / 2
                d.rectangle([sx - 3, height - bh - sh, sx + 3, height - bh],
                            fill=(255, 255, 255, 255))
    return img


def stripes(width=2048, height=512, seed=3, count=7, angle=18, taper=0.6):
    """Tapered speed stripes — the classic body-line accent, done crisply."""
    img = Image.new("RGBA", (width * 2, height * 2), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    rng = random.Random(seed)
    for i in range(count):
        y = (i + 0.5) / count * height * 2
        th = height * 0.05 * rng.uniform(0.5, 1.5)
        d.polygon([(0, y - th), (width * 2, y - th * taper),
                   (width * 2, y + th * taper), (0, y + th)],
                  fill=(255, 255, 255, 255))
    return img.rotate(angle, resample=Image.BICUBIC, expand=False) \
              .crop((width // 2, height // 2, width // 2 + width, height // 2 + height))


SHAPES = {
    "mountains": {"fn": mountains, "name": "Mountain Ridgeline", "seamless": True,
                  "hint": "Layered peaks with aerial depth. Wraps the car seamlessly."},
    "treeline": {"fn": treeline, "name": "Pine Treeline", "seamless": True,
                 "hint": "Conifer horizon. Wraps seamlessly along a rocker or lower door."},
    "skyline": {"fn": skyline, "name": "City Skyline", "seamless": True,
                "hint": "Blocky urban horizon with spires. Wraps seamlessly."},
    # Rotation is what makes the stripes look right and also what breaks the
    # wrap - the angled ends cannot meet. Place it on a panel, do not tile it.
    "stripes": {"fn": stripes, "name": "Speed Stripes", "seamless": False,
                "hint": "Tapered angled accents for body lines. Does NOT tile - place on a panel."},
}


def render(shape, **kw):
    spec = SHAPES.get(shape)
    if not spec:
        raise KeyError(shape)
    fn = spec["fn"]
    allowed = fn.__code__.co_varnames[:fn.__code__.co_argcount]
    return fn(**{k: v for k, v in kw.items() if k in allowed})
